name: rust-build-and-tests
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}-onlyswaps
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-build-and-tests:
    name: Build and test rust crates
    runs-on: ["randamu-self-hosted-default"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # 1. Compile onlyswaps-solidity
      - name: Cache npm onlyswaps-solidity
        uses: actions/cache@v3
        with:
          path: onlyswaps-solidity/node_modules
          key: ${{ runner.os }}-npm-onlyswaps-solidity-${{ hashFiles('onlyswaps-solidity/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-onlyswaps-solidity-

      - name: onlyswaps-solidity - Install dependencies
        working-directory: ./onlyswaps-solidity
        run: npm ci

      - name: Cache Solidity onlyswaps-solidity
        uses: actions/cache@v3
        with:
          path: onlyswaps-solidity/out
          key: ${{ runner.os }}-sol-onlyswaps-solidity-${{ hashFiles('onlyswaps-solidity/src/**/*.sol', 'onlyswaps-solidity/lib/**/*.sol') }}
          restore-keys: |
            ${{ runner.os }}-sol-onlyswaps-solidity-

      - name: onlyswaps-solidity - Build Solidity contracts
        working-directory: ./onlyswaps-solidity
        run: npm run build:forge

      # 2. Build and test workspace packages
      - name: Lint & Test Rust Workspace
        uses: ./.github/actions/rust-test-action
        with:
          working-directory: .
          extra-cache-key: 'onlyswaps-solver'